# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20161211_1736'),
        ('scrumboard', '0002_auto_20161118_1949'),
    ]

    operations = [
    ]
